config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'lists#index'

  resources :lists, except: %i[edit update destroy] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
  delete "lists/:id", to: "lists#destroy", as: "list_delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id, message: 'is already in the list' }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/new.html.erb
<div class="m-1">
  <h1>New Bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, input_html: {data: {controller: "tom-select"}} %>
    <%= f.input :comment %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1 class="m-1"><%= link_to("Watch list", root_path, class: "m-3 text-decoration-none text-dark") %></h1>
    </header>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="m-3">
  <h1>Lists</h1>
  <%= "You havn't created any lists yet!" if @lists.empty? %>
  <div class="d-flex h-25">
    <% @lists.each do |list| %>
      <div class="card-category w-25 h-100" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3), url('<%= list.photo.attached? ? cl_image_tag(list.photo.key) : asset_path('list_background.jpg') %>'))">
        <%=  %>
        <%= link_to(list.name, list_path(list), class: "text-decoration-none") %>
        <%= link_to("Remove", list_delete_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "ms-2 mb-2 text-danger text-decoration-none") %>
      </div>
    <% end %>
  </div>
  <p><%= link_to("New list", new_list_path, class: "text-decoration-none") %></p>
</div>

<%= cl_image_tag("eogdvy4sw8i9xadla35qxfa6eoev", width: 400, height: 300, crop: :fill) %>

app/views/lists/new.html.erb
<div class="m-1">
  <h1>New list</h1>
  <%= simple_form_for [@list] do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="d-flex justify-content-between m-3">
  <h2 class="m-0"><%= @list.name %></h2>
  <button class="btn btn-outline-primary p-1"><%= link_to("Add bookmark", new_list_bookmark_path(@list), class: "text-decoration-none") %></button>
</div>

<div class="mb-3">
  <p class="ms-3"><%= "You havn't saved any movies yet!" if @list.movies.empty? %></p>
  <% @list.bookmarks.each do |bookmark| %>
    <div class="d-flex m-3 bg-white shadow-sm", style="height: 200px;">
      <%= image_tag(bookmark.movie.poster_url, class: "card-img-left") %>
      <div class="p-3 pb-0">
        <div class="d-flex align-items-center">
          <h2><%= bookmark.movie.title %></h2>
          <div class="ms-2 d-flex align-items-center">
            <h5>Rating</h5>
            <p class="ms-1 mb-2"><%= bookmark.movie.rating %></p>
          </div>
          <%= link_to("Remove", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "ms-2 mb-2 text-danger text-decoration-none") %>
        </div>
        <div>
          <h5>Overview</h5>
          <p><%= bookmark.movie.overview %></p>
        </div>
        <div>
          <h5>Your comment</h5>
          <p><%= bookmark.comment %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>